# Generated by Django 5.2.4 on 2025-07-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="train",
            old_name="cargo_num",
            new_name="cargo",
        ),
        migrations.RenameField(
            model_name="train",
            old_name="places_in_cargo",
            new_name="seats_in_cargo",
        ),
    ]
